// src/components/header/DesktopHeader.svelte
<script lang="ts">
  import type { ClassValue } from "svelte/elements";

  import Link from "@/components/Link.svelte";
  import { AUTHOR } from "@/config/constants";

  import HeaderNavigationItems from "./HeaderNavigationItems.svelte";

  interface Props {
    class: ClassValue;
    pathname: string;
  }

  const { class: className, pathname }: Props = $props();
</script>

<header class={["border-b bg-background/80 backdrop-blur", className]}>
  <div
    class="min-h-header mx-auto flex max-w-3xl items-center justify-between px-4"
  >
    <Link class="text-xl font-semibold" href="/">
      {AUTHOR.name}
    </Link>

    <nav>
      <ul class="flex gap-4 rounded font-medium">
        <HeaderNavigationItems {pathname} />
      </ul>
    </nav>
  </div>
</header>

// src/components/header/DesktopHeader.tsx
import { cn } from "cn";

import { HeaderNavigationItems } from "@/components/header/HeaderNavigationItems";
import { Link } from "@/components/Link";
import { AUTHOR } from "@/config/constants";

interface Props {
  className: string;
  pathname: string;
}

export function DesktopHeader({ className, pathname }: Props) {
  return (
    <header className={cn("border-b bg-background/80 backdrop-blur", className)}>
      <div className="min-h-header mx-auto flex max-w-3xl items-center justify-between px-4">
        <Link className="text-xl font-semibold" href="/">
          {AUTHOR.name}
        </Link>

        <nav>
          <ul className="flex gap-4 rounded font-medium">
            <HeaderNavigationItems pathname={pathname} />
          </ul>
        </nav>
      </div>
    </header>
  );
}
