// src/components/header/Header.svelte
<script lang="ts">
  import Link from "@/components/Link.svelte";
  import Button from "@/components/ui/button/Button.svelte";
  import { AUTHOR } from "@/config/constants";
  import { MenuClosedIcon, MenuOpenIcon } from "@/config/icons.svelte";
  import { cn } from "@/lib/utils";

  import HeaderNavigationItems from "./HeaderNavigationItems.svelte";

  interface Props {
    pathname: string;
  }

  const { pathname }: Props = $props();

  let expandMobileNav = $state(false);
</script>

<header
  class="sticky top-0 z-20 w-full border-b bg-background/80 backdrop-blur"
>
  <nav
    class="min-h-header mx-auto flex max-w-3xl flex-wrap items-center justify-between p-4"
  >
    <Link href="/">
      <span class="text-xl font-semibold whitespace-nowrap">{AUTHOR.name}</span>
    </Link>

    <Button
      class={cn(
        "transition-transform duration-200 md:hidden",
        expandMobileNav ? "rotate-90" : "rotate-0",
      )}
      variant="outline"
      size="icon"
      aria-label={expandMobileNav ? "Close menu" : "Open menu"}
      aria-expanded={expandMobileNav}
      aria-controls="mobile-nav"
      onclick={() => {
        expandMobileNav = !expandMobileNav;
      }}
    >
      {#if expandMobileNav}
        <MenuOpenIcon />
      {:else}
        <MenuClosedIcon />
      {/if}
    </Button>

    <div
      class="hidden w-full data-[expanded=true]:block md:block md:w-auto"
      id="mobile-nav"
      data-expanded={expandMobileNav}
    >
      <ul
        class="flex rounded font-medium not-md:mt-4 not-md:flex-col not-md:border not-md:bg-background/80 not-md:p-4 md:space-x-8"
      >
        <HeaderNavigationItems {pathname} />
      </ul>
    </div>
  </nav>
</header>

// src/components/header.tsx
"use client";

import { useState } from "react";

import { Link } from "@/components/link";
import { Button } from "@/components/ui/button";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
} from "@/components/ui/navigation-menu";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { AUTHOR, NAV_ITEMS } from "@/config/constants";
import { MenuClosedIcon } from "@/config/icons";
import type { Route } from "@/types";

export interface HeaderProps {
  pathname: string;
}

export function Header({ pathname }: HeaderProps) {
  const [openSheet, setOpenSheet] = useState(false);

  const isActive = (href: Route) => {
    if (href === "/") {
      return pathname === "/";
    }

    return pathname.startsWith(href);
  };

  const navigation = NAV_ITEMS.map((item) => {
    return (
      <NavigationMenuItem className="not-sm:w-full" key={item.href}>
        <NavigationMenuLink
          active={isActive(item.href)}
          render={<Link href={item.href} aria-label={item.label} />}
        >
          {item.label}
        </NavigationMenuLink>
      </NavigationMenuItem>
    );
  });

  return (
    <header className="sticky top-0 z-10 border-b bg-background/80 backdrop-blur">
      <NavigationMenu className="h-header mx-auto max-w-3xl justify-between px-10">
        <Link className="text-xl font-semibold whitespace-nowrap" href="/">
          {AUTHOR.name}
        </Link>

        <NavigationMenuList className="flex justify-end gap-2 not-sm:hidden">
          {navigation}
        </NavigationMenuList>

        <Sheet open={openSheet} onOpenChange={setOpenSheet}>
          <SheetTrigger
            className="sm:hidden"
            render={
              <Button variant="ghost" size="icon">
                <MenuClosedIcon />
              </Button>
            }
          />

          <SheetContent className="p-10" side="top">
            <NavigationMenuList className="flex-col">{navigation}</NavigationMenuList>
          </SheetContent>
        </Sheet>
      </NavigationMenu>
    </header>
  );
}
