// src/components/link.tsx
import { ExternalLinkIcon } from "@/config/icons";
import { cn } from "@/lib/utils";

export interface LinkProps extends React.ComponentProps<"a"> {
  showExternalLinkIcon?: boolean;
}

export function Link({
  className,
  children,
  href,
  rel,
  target,
  showExternalLinkIcon,
  ...props
}: LinkProps) {
  const isExternal = __isExternal(href);
  const resolvedShowExternalLinkIcon = showExternalLinkIcon ?? isExternal;

  return (
    <a
      className={cn(
        resolvedShowExternalLinkIcon && "inline-flex place-items-center gap-1",
        className,
      )}
      href={href}
      rel={rel ?? (isExternal ? "noopener noreferrer" : undefined)}
      target={target ?? (isExternal ? "_blank" : undefined)}
      {...props}
    >
      {children}
      {resolvedShowExternalLinkIcon && <ExternalLinkIcon />}
    </a>
  );
}

function __isExternal(href: LinkProps["href"]): boolean {
  if (href === undefined) {
    return false;
  }

  return !(href.startsWith("/") || href.startsWith("?") || href.startsWith("#"));
}

// src/components/Link.svelte
<script lang="ts">
  import type { HTMLAnchorAttributes } from "svelte/elements";

  import { ExternalLinkIcon } from "@/config/icons.svelte";
  import { cn } from "@/lib/utils";

  interface Props extends HTMLAnchorAttributes {
    showExternalLinkIcon?: boolean;
  }

  const {
    class: className,
    href,
    rel,
    target,
    showExternalLinkIcon,
    children,
    ...props
  }: Props = $props();

  function __isExternal(): boolean {
    if (href === undefined || href === null) {
      return false;
    }

    return !(
      href.startsWith("/") ||
      href.startsWith("?") ||
      href.startsWith("#")
    );
  }

  const isExternal = __isExternal();
  const resolvedShowExternalLinkIcon = $derived(
    showExternalLinkIcon ?? isExternal,
  );
</script>

<a
  class={cn(
    resolvedShowExternalLinkIcon && "inline-flex place-items-center gap-1",
    className,
  )}
  {href}
  rel={rel ?? (isExternal ? "noopener noreferrer" : undefined)}
  target={target ?? (isExternal ? "_blank" : undefined)}
  {...props}
>
  {@render children?.()}

  {#if resolvedShowExternalLinkIcon}
    <ExternalLinkIcon />
  {/if}
</a>
