// src/components/ui/button-group/ButtonGroupSeparator.svelte
<script lang="ts">
  import type { ComponentProps } from "svelte";

  import Separator from "@/components/ui/Separator.svelte";
  import { cn } from "@/lib/utils";

  type Props = ComponentProps<typeof Separator>;

  const {
    class: className,
    orientation = "vertical",
    ...props
  }: Props = $props();
</script>

<Separator
  data-slot="button-group-separator"
  data-orientation={orientation}
  // orientation={orientation}
  class={cn(
    "relative self-stretch bg-input data-horizontal:mx-px data-horizontal:w-auto data-vertical:my-px data-vertical:h-auto",
    className,
  )}
  {...props}
></Separator>

// src/components/ui/button-group/button-group-separator.tsx
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";

type Props = React.ComponentProps<typeof Separator>;

export function ButtonGroupSeparator({ className, orientation = "vertical", ...props }: Props) {
  return (
    <Separator
      data-slot="button-group-separator"
      data-orientation={orientation}
      // orientation={orientation}
      className={cn(
        "relative self-stretch bg-input data-horizontal:mx-px data-horizontal:w-auto data-vertical:my-px data-vertical:h-auto",
        className,
      )}
      {...props}
    />
  );
}
