// src/components/ui/button-group/ButtonGroupText.tsx
import { cn } from "cn";

interface Props extends React.HTMLAttributes<HTMLDivElement> {
  orientation?: "horizontal" | "vertical";
}

export function ButtonGroupText({ className, ...props }: Props) {
  return (
    <div
      data-slot="button-group-text"
      className={cn(
        "flex items-center gap-2 rounded-2xl border bg-muted px-2.5 text-sm font-medium [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4",
        className,
      )}
      {...props}
    />
  );
}

// src/components/ui/button-group/ButtonGroupText.svelte
<script lang="ts">
  import type { SvelteHTMLElements } from "svelte/elements";
  import { cn } from "cn";

  type DivProps = SvelteHTMLElements["div"];
  interface Props extends DivProps {
    orientation?: "horizontal" | "vertical";
  }

  const { class: className, children, ...props }: Props = $props();
</script>

<div
  data-slot="button-group-text"
  class={cn(
    "flex items-center gap-2 rounded-2xl border bg-muted px-2.5 text-sm font-medium [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4",
    className,
  )}
  {...props}
>
  {@render children?.()}
</div>
