// src/components/ui/button-group/ButtonGroup.svelte
<script lang="ts">
  import type { VariantProps } from "class-variance-authority";
  import type { HTMLFieldsetAttributes } from "svelte/elements";

  import { cn } from "@/lib/utils";

  import { buttonGroupVariants } from "./variants";

  type Props = HTMLFieldsetAttributes &
    VariantProps<typeof buttonGroupVariants>;

  const { class: className, orientation, children, ...props }: Props = $props();
</script>

<fieldset
  data-slot="button-group"
  data-orientation={orientation}
  class={cn(buttonGroupVariants({ orientation }), className)}
  {...props}
>
  {@render children?.()}
</fieldset>

// src/components/ui/button-group/button-group.tsx
import type { VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";

import { buttonGroupVariants } from "./variants";

type Props = React.ComponentProps<"fieldset"> & VariantProps<typeof buttonGroupVariants>;

export function ButtonGroup({ className, orientation, children, ...props }: Props) {
  return (
    <fieldset
      data-slot="button-group"
      data-orientation={orientation}
      className={cn(buttonGroupVariants({ orientation }), className)}
      {...props}
    >
      {children}
    </fieldset>
  );
}
