// src/components/ui/button-group/ButtonGroupText.svelte
<script lang="ts">
  import type { SvelteHTMLElements } from "svelte/elements";

  import { cn } from "@/lib/utils";

  type DivProps = SvelteHTMLElements["div"];
  interface Props extends DivProps {
    orientation?: "horizontal" | "vertical";
  }

  const { class: className, children, ...props }: Props = $props();
</script>

<div
  data-slot="button-group-text"
  class={cn(
    "flex items-center gap-2 rounded-2xl border bg-muted px-2.5 text-sm font-medium [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4",
    className,
  )}
  {...props}
>
  {@render children?.()}
</div>

// src/components/ui/button-group/button-group-text.tsx
import { cn } from "@/lib/utils";

type Props = React.ComponentProps<"div">;

export function ButtonGroupText({ className, children, ...props }: Props) {
  return (
    <div
      className={cn(
        "flex items-center gap-2 rounded-4xl border bg-muted px-2.5 text-sm font-medium [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4",
        className,
      )}
      data-slot="button-group-text"
      {...props}
    >
      {children}
    </div>
  );
}
