// src/components/ui/Separator.svelte
<script lang="ts">
  import type { SvelteHTMLElements } from "svelte/elements";
  import { cn } from "cn";

  interface Props extends Omit<SvelteHTMLElements["div"], "children"> {
    orientation?: "horizontal" | "vertical";
  }

  const {
    class: className,
    orientation = "horizontal",
    ...props
  }: Props = $props();
</script>

<div
  role="separator"
  aria-orientation={orientation}
  data-slot="separator"
  data-orientation={orientation}
  class={cn(
    "shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch",
    className,
  )}
  {...props}
></div>

// src/components/ui/Separator.tsx
import { cn } from "cn";

interface Props extends Omit<React.HTMLAttributes<HTMLDivElement>, "children"> {
  orientation?: "horizontal" | "vertical";
}

export function Separator({ className, orientation = "horizontal", ...props }: Props) {
  return (
    <div
      role="separator"
      aria-orientation={orientation}
      data-slot="separator"
      data-orientation={orientation}
      className={cn(
        "shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch",
        className,
      )}
      {...props}
    />
  );
}
